$ErrorActionPreference = 'Stop'
$path = Join-Path $PSScriptRoot 'index.md'
$pairs = @(
    @('title="Changelog" subtitle="User-facing changes only. Internal maintenance and infrastructure updates are omitted."', 'title="История изменений" subtitle="Только изменения для пользователей. Внутренние правки и обновления инфраструктуры опущены."'),
    @('**Features**', '**Новые возможности**'),
    @('**Improvements**', '**Улучшения**'),
    @('**Bug Fixes**', '**Исправления ошибок**'),
    @('**Breaking Changes**', '**Несовместимые изменения**'),
    @('**Security**', '**Безопасность**'),
    @('Added OpenHands integration with native MCP configuration and built-in recall/retain rules.', 'Добавлена интеграция OpenHands со встроенной настройкой MCP и правилами извлечения и сохранения памяти.'),
    @('Added Zed editor integration via an MCP context server with recall/retain rules.', 'Добавлена интеграция с редактором Zed через сервер контекста MCP с правилами извлечения и сохранения памяти.'),
    @('Added Continue.dev integration via an HTTP context provider.', 'Добавлена интеграция Continue.dev через HTTP-поставщик контекста.'),
    @('Added Composio integration so Hindsight memory can be used as custom tools.', 'Добавлена интеграция Composio: память Hindsight можно применять как свои инструменты.'),
    @('Added a Zapier app with actions and REST-hook triggers for automating workflows with Hindsight.', 'Добавлено приложение Zapier с действиями и триггерами REST-хуков для автоматизации работы с Hindsight.'),
    @('Added a dry-run fact extraction API endpoint to preview extraction results without saving them.', 'Добавлена конечная точка API для пробного извлечения фактов: результат можно посмотреть без сохранения.'),
    @('Added optional MarkItDown-based OCR support for extracting text from documents.', 'Добавлена необязательная поддержка OCR на базе MarkItDown для извлечения текста из документов.'),
    @('Improved Chinese temporal query understanding for more accurate time-based searches.', 'Улучшено понимание запросов о времени на китайском языке для более точного поиска.'),
    @('Added tool annotations (read-only/destructive hints) to MCP tools for safer client behavior.', 'Для инструментов MCP добавлены пометки о чтении и опасных действиях, чтобы клиент работал безопаснее.'),
    @('Added support for the "shared" observation scope across consolidation and the Control Plane UI.', 'Область наблюдений "shared" теперь поддерживается при консолидации и в интерфейсе Control Plane.'),
    @('Added support for exact tag matching (tags_match=exact) across the UI and client libraries.', 'Точное совпадение тегов (tags_match=exact) теперь поддерживается в интерфейсе и клиентских библиотеках.'),
    @('Added Intel XPU detection to enable local embedding acceleration when available.', 'Добавлено обнаружение Intel XPU для ускорения локального создания векторов, если устройство доступно.'),
    @('Exposed additional operation/worker backlog metrics to make async processing health easier to monitor.', 'Добавлены метрики очереди операций и рабочих процессов для контроля асинхронной обработки.'),
    @('Added Gemini service tier configuration options.', 'Добавлены настройки уровня обслуживания Gemini.'),
    @('API responses now omit wire-safe null fields to reduce payload size.', 'Ответы API теперь опускают поля со значением null, когда это безопасно для формата передачи, чтобы уменьшить объём данных.'),
    @('Improved search recency scoring using effective-time fallback for better ranking of results.', 'Улучшена оценка свежести результатов поиска: если нужно, берётся время действия записи.'),
    @('Parallelized tenant schema migrations to reduce migration time on multi-tenant deployments.', 'Миграции схем для нескольких арендаторов теперь идут параллельно и занимают меньше времени.'),
    @('Fixed retain chunking so oversized documents no longer lose content when split into multiple sub-batches.', 'Исправлено разбиение больших документов при сохранении: текст больше не теряется при делении на несколько партий.'),
    @('Fixed MCP so custom tool instructions are applied correctly again.', 'Исправлен MCP: свои инструкции для инструментов снова применяются верно.'),
    @('MCP responses no longer include reflect tool/LLM traces by default, preventing unexpected extra output.', 'Ответы MCP по умолчанию больше не содержат трассировки инструмента reflect и языковой модели.'),
    @('Prevented hung LiteLLM calls from blocking forever by enforcing a hard timeout.', 'Для вызовов LiteLLM задано жёсткое время ожидания, чтобы зависший вызов не блокировал работу навсегда.'),
    @('Fixed bank listing so bank-config disposition and mission overlays are applied consistently.', 'В списке банков теперь единообразно применяются настройки характера банка и наложения задач.'),
    @('Dry-run extraction now rejects empty/whitespace inputs and runs only after passing the precheck step.', 'Пробное извлечение теперь отклоняет пустой текст и запускается лишь после начальной проверки.'),
    @("Fixed consolidation when the LLM returns single-value source_fact_ids so runs don’t fail unexpectedly.", 'Консолидация больше не срывается, если языковая модель возвращает одно значение source_fact_ids.'),
    @('Fixed metric labeling for HTTP endpoints so bank IDs are templated correctly (avoids high-cardinality labels).', 'Исправлены метки метрик для HTTP-точек: ID банков подставляются по шаблону, чтобы число меток не росло без нужды.'),
    @('Fixed provider quota reset behavior by deferring retries to avoid unnecessary retry storms.', 'После сброса квоты поставщика повторы запросов откладываются, чтобы не создавать лавину вызовов.'),
    @('Honored CODEX_HOME for locating Codex auth.json, fixing auth in custom home directories.', 'Для поиска Codex auth.json теперь учитывается CODEX_HOME; вход работает и при своём домашнем каталоге.'),
    @('Fixed the Control Plane so the “shared” observation scope is selectable in the Add Document UI.', 'В интерфейсе добавления документа Control Plane теперь можно выбрать область наблюдений “shared”.'),
    @('Improved output sanitization by stripping malformed reasoning tags/blocks from non-structured outputs.', 'Из неструктурированных ответов теперь удаляются неверно оформленные теги и блоки рассуждений.'),
    @('Added support for observation scopes, including listing, filtering, visualization, and per-scope observation limits.', 'Добавлена поддержка областей наблюдений: списки, фильтрация, показ и лимиты наблюдений для каждой области.'),
    @('Added SIEM-focused enrichment fields to Memory Defense webhook events to improve downstream security alert context.', 'В события вебхука Memory Defense добавлены поля для SIEM, чтобы оповещения безопасности содержали больше контекста.'),
    @('Introduced reversible memory curation so memory units can be edited, invalidated, and reverted.', 'Добавлена обратимая правка памяти: её элементы можно менять, помечать недействительными и возвращать к прежнему виду.'),
    @('Added per-bank provider cost attribution using the OpenAI "user" field.', 'Расходы на поставщика теперь можно учитывать по банкам через поле OpenAI "user".'),
    @('Added a native Nous Portal LLM provider with OAuth authentication (no external CLI dependency).', 'Добавлен встроенный поставщик языковых моделей Nous Portal со входом через OAuth без внешней командной строки.'),
    @('Added a per-bank LLM connectivity probe to help verify provider configuration.', 'Добавлена проверка связи с языковой моделью для каждого банка, чтобы проверять настройки поставщика.'),
    @('Added Gemini Batch API support for retain fact extraction.', 'Для извлечения фактов при сохранении добавлена поддержка Gemini Batch API.'),
    @('Added support for the Gemini embedding-2 model family (per-input embeddings).', 'Добавлена поддержка семейства Gemini embedding-2 с векторами для каждого входного текста.'),
    @('Improved retain ingestion by chunking JSONL files on line boundaries to avoid splitting records.', 'При загрузке памяти файлы JSONL теперь делятся по строкам, чтобы записи не разрывались.'),
    @('Added an option in the UI to export a constellation as a shareable SVG poster.', 'В интерфейсе добавлен экспорт созвездия в SVG-плакат, которым можно поделиться.'),
    @('Added a Cursor plugin providing Hindsight persistent memory integration.', 'Добавлен плагин Cursor с долговременной памятью Hindsight.'),
    @('Added a pip-installable Cline integration package (hindsight-cline).', 'Добавлен пакет интеграции Cline для установки через pip (hindsight-cline).'),
    @('Added a pip-installable Cursor CLI integration package (hindsight-cursor-cli).', 'Добавлен пакет интеграции Cursor CLI для установки через pip (hindsight-cursor-cli).'),
    @('Added Hindsight memory integration for Microsoft Agent Framework (no MCP required).', 'Добавлена интеграция памяти Hindsight с Microsoft Agent Framework без MCP.'),
    @('Added a local Control Center web app for embedded deployments.', 'Для встроенных установок добавлено локальное веб-приложение Control Center.'),
    @('Improved reflect synthesis to better respect directives and language rules in final outputs.', 'Синтез ответа reflect теперь точнее соблюдает указания и правила языка.'),
    @('Added support for selecting Amazon Bedrock service tier.', 'Добавлен выбор уровня обслуживания Amazon Bedrock.'),
    @('Fixed the control-plane bank view to avoid double-loading graph data, improving performance and reducing redundant requests.', 'Экран банка в Control Plane больше не загружает граф дважды, что ускоряет работу и убирает лишние запросы.'),
    @('Fixed per-scope observation limiting so a limit of 0 correctly prevents new observations from being created.', 'Лимит наблюдений по области теперь работает верно: значение 0 запрещает создавать новые наблюдения.'),
    @('Improved cancellation handling so abandoned recall/reflect operations can be reliably cancelled on disconnect.', 'При разрыве связи оставшиеся операции recall и reflect теперь надёжно отменяются.'),
    @('Fixed a concurrency issue where model initialization could change the global Torch default dtype, ensuring consistent float32 behavior.', 'Исправлена гонка: запуск модели больше не меняет глобальный тип данных Torch по умолчанию, поэтому float32 ведёт себя одинаково.'),
    @('Fixed webhook payloads to include previously missing fields.', 'В данных вебхуков добавлены поля, которые прежде пропускались.'),
    @('Fixed PostgreSQL history storage by widening history bank_id to TEXT to prevent failures with longer IDs.', 'Для хранения истории в PostgreSQL поле bank_id переведено в TEXT, чтобы длинные ID не вызывали сбой.'),
    @('Fixed the CLI to correctly parse get-memory responses.', 'Командная строка теперь верно разбирает ответы get-memory.'),
    @('Fixed the control-plane meeting notes flow to drop empty messages that could fail locale validation.', 'При создании заметок встречи Control Plane теперь убирает пустые сообщения, на которых могла сбоить проверка локали.'),
    @('Improved rolling-deployment migration skipping to handle wrapped dependency-resolution errors more reliably.', 'При поэтапном развёртывании пропуск миграций теперь надёжнее обрабатывает вложенные ошибки поиска зависимостей.'),
    @('Add an API configuration flag to skip storing raw document text.', 'Добавлен флаг API, который отключает хранение исходного текста документа.'),
    @('Add an Oh-My-OpenAgent (OMO) integration for connecting Hindsight memory to OMO workflows.', 'Добавлена интеграция Oh-My-OpenAgent (OMO) с памятью Hindsight.'),
    @('Add a Cline integration that hooks into lifecycle events to save and retrieve Hindsight memory.', 'Добавлена интеграция Cline: хуки событий сохраняют и извлекают память Hindsight.'),
    @('Add a Haystack integration to use Hindsight as a memory component in Haystack pipelines.', 'Добавлена интеграция Haystack, где Hindsight служит памятью для конвейеров.'),
    @('Add a Cursor CLI integration for capturing and using Hindsight memory from Cursor workflows.', 'Добавлена интеграция Cursor CLI для записи и применения памяти Hindsight в процессах Cursor.'),
    @('Introduce an official Obsidian plugin to sync and use Hindsight memory from Obsidian.', 'Добавлен официальный плагин Obsidian для синхронизации и применения памяти Hindsight.'),
    @('Package the Roo Code integration as an installable PyPI CLI (hindsight-roo-code).', 'Интеграция Roo Code выпущена как пакет PyPI с командной строкой (hindsight-roo-code).'),
    @("Fix vector index behavior to avoid forcing vchordrq.probes settings on vchord indexes that don't support it.", 'Настройка vchordrq.probes больше не навязывается индексам vchord, которые её не поддерживают.'),
    @('Ensure database maintenance routines are installed correctly when using the public schema.', 'Служебные процедуры базы данных теперь верно ставятся и при схеме public.'),
    @('Add periodic background maintenance to reconcile consolidation state and enforce retention across tenants.', 'Добавлено фоновое обслуживание по расписанию: оно согласует состояние консолидации и соблюдает сроки хранения у всех арендаторов.'),
    @('Add durable progress snapshots for long-running consolidation and batch retain operations, so status can be resumed/inspected reliably.', 'Для долгой консолидации и пакетного сохранения памяти добавлены устойчивые снимки прогресса: состояние можно верно посмотреть и продолжить.'),
    @('Enable LLM request tracing by default (with per-bank support) and retain traces for 1 day for easier debugging/observability.', 'Трассировка запросов к языковой модели включена по умолчанию, в том числе по банкам; записи хранятся сутки для отладки.'),
    @('Add semantic deduplication of near-duplicate observations during consolidation (enabled by default, except on Oracle).', 'При консолидации добавлено смысловое удаление почти одинаковых наблюдений. Оно включено по умолчанию, кроме Oracle.'),
    @('Store mental-model and observation history in dedicated database tables for better scalability and reliability.', 'История ментальных моделей и наблюдений вынесена в отдельные таблицы базы данных для надёжной работы при росте объёма.'),
    @('Add a local ONNX embeddings provider so embeddings can be generated without a hosted embeddings API.', 'Добавлен локальный поставщик векторов ONNX: векторы можно создавать без внешнего API.'),
    @('Add whole-bank export/import for cross-instance migration.', 'Добавлены экспорт и импорт целого банка для переноса между экземплярами.'),
    @('Add document export/import between banks without re-running the LLM (reusing previously extracted results).', 'Документы можно переносить между банками без нового вызова языковой модели, используя уже извлечённые данные.'),
    @('Add provider-agnostic prompt-prefix caching (default on) to reduce repeated LLM work for retain, consolidation, and reflect.', 'Добавлен общий для всех поставщиков кэш начала запроса. Он включён по умолчанию и снижает число повторных вызовов модели при сохранении, консолидации и reflect.'),
    @('Add global support for sending extra provider request fields via HINDSIGHT_API_LLM_EXTRA_BODY.', 'Через HINDSIGHT_API_LLM_EXTRA_BODY теперь можно добавлять поля в запросы к любому поставщику.'),
    @('Honor HINDSIGHT_API_LLM_STRICT_SCHEMA across all JSON-schema capable LLM providers for stricter structured outputs.', 'Параметр HINDSIGHT_API_LLM_STRICT_SCHEMA теперь действует у всех поставщиков моделей с поддержкой JSON Schema для строгого формата ответов.'),
    @('Add Superagent safety middleware integration for safer agent execution.', 'Добавлена интеграция защитного промежуточного слоя Superagent для более безопасной работы агентов.'),
    @('Improve client SDK trace visibility by exposing reflect tool/LLM call details in the Python and TypeScript wrappers.', 'Обёртки Python и TypeScript теперь показывают в трассировке детали вызовов инструмента reflect и языковой модели.'),
    @('Allow tuning recall behavior with configurable per-strategy retrieval boosts via environment configuration.', 'Через переменные среды можно задать усиление поиска для каждой стратегии извлечения памяти.'),
    @('Allow tuning semantic recall sensitivity with a configurable minimum similarity threshold (HINDSIGHT_API_SEMANTIC_MIN_SIMILARITY).', 'Чувствительность смыслового поиска можно менять через порог сходства HINDSIGHT_API_SEMANTIC_MIN_SIMILARITY.'),
    @('Avoid an unnecessary extra LLM call during reflect when a fresh mental model can be used directly.', 'Если свежая ментальная модель подходит для reflect, лишний вызов языковой модели больше не нужен.'),
    @('Speed up and reduce load from bank statistics queries via caching and more efficient computation.', 'Запросы статистики банка стали быстрее и легче за счёт кэша и более точного расчёта.'),
    @('Improve visibility when audit logs or LLM requests are disabled by showing a clear "not enabled" splash in the control plane UI.', 'Если аудит или запросы к языковой модели отключены, интерфейс Control Plane ясно показывает это.'),
    @('Improve OpenCode integration observability with clearer debug logging, endpoint reporting, and surfaced errors.', 'В интеграции OpenCode улучшены журналы отладки, показ конечной точки и ошибок.'),
    @('Fix consolidation runs failing or truncating output by enforcing an explicit output token budget.', 'Для консолидации задан явный лимит токенов ответа, чтобы операции не срывались и не обрезали результат.'),
    @('Reduce slow/expensive temporal recall paths by limiting how many entries are scanned per fact type.', 'Поиск по времени стал быстрее и дешевле: число просматриваемых записей ограничено для каждого типа фактов.'),
    @('Fix pgroonga BM25 search failures by escaping query text properly.', 'Исправлены сбои поиска pgroonga BM25 за счёт верного экранирования текста запроса.'),
    @('Preserve correct RRF (fusion) source ranks in retrieval traces/results.', 'В трассировках и результатах поиска сохранены верные исходные ранги RRF.'),
    @('Prevent the API from hanging indefinitely at startup by failing fast when model initialization blocks.', 'API больше не висит при запуске: если инициализация модели блокируется, ошибка выдаётся сразу.'),
    @('Fix recall and mental-model history support when using the Oracle database backend.', 'Исправлена работа истории извлечения памяти и ментальных моделей с базой Oracle.'),
    @('Validate embedding vector dimensions before writing to pgvector to prevent storage/query errors.', 'Перед записью в pgvector проверяется размерность векторов, чтобы избежать ошибок хранения и поиска.'),
    @('Improve retain concurrency safety by rechecking freshness before extraction and serializing concurrent writes to the same document.', 'Перед извлечением фактов повторно проверяется свежесть; одновременная запись в один документ идёт по очереди.'),
    @('Fix incorrect fact attribution during retain caused by bank routing key leakage.', 'Исправлена неверная привязка фактов при сохранении из-за утечки ключа маршрутизации банка.'),
    @('Fix mental model creation failures by ensuring the bank exists before inserting the model.', 'Перед записью ментальной модели проверяется наличие банка, чтобы её создание не срывалось.'),
    @('Fix external Postgres setups using vchord by adding required catalogs to the session search_path.', 'Для внешнего Postgres с vchord нужные каталоги добавлены в search_path сеанса.'),
    @('Improve Docker standalone diagnostics by providing a clear error when pg0 bind-mount permissions prevent startup.', 'Отдельный запуск в Docker теперь ясно сообщает об ошибке прав на bind-mount pg0.'),
    @('Improve compatibility with LLM servers that mishandle tool_choice="required" by falling back to a safer tool-choice mode.', 'Если сервер модели неверно обрабатывает tool_choice="required", система переходит на более совместимый режим выбора инструмента.'),
    @('Fix Bedrock IAM authentication with the LiteLLM reranker by making the reranker API key optional.', 'Ключ API переранжирования стал необязательным, чтобы вход через Bedrock IAM работал с LiteLLM.'),
    @('Expose retain outcome metadata so users can see what happened during a retain operation.', 'Добавлены метаданные итога сохранения памяти, чтобы было видно, что произошло.'),
    @('Make bank config PATCH persist correctly even for banks that have never retained data yet.', 'Изменения настроек банка через PATCH теперь сохраняются и для банков, где ещё нет данных.'),
    @('Prevent fact extraction prompt formatting from breaking extraction by removing Markdown bold markers.', 'Из запроса для извлечения фактов убраны маркеры жирного текста Markdown, которые мешали извлечению.'),
    @('Improve recall stability/performance by gating VectorChord BM25 usage and applying per-source candidate caps.', 'Поиск памяти стал устойчивее и быстрее: VectorChord BM25 применяется при нужном условии, а число кандидатов ограничено для каждого источника.'),
    @('Fix control plane UI localization issues for operations and graph legends.', 'Исправлен перевод операций и подписей графа в интерфейсе Control Plane.'),
    @('Improve transfer import reporting by including mental_model_history counts in CLI summaries.', 'Сводки импорта в командной строке теперь показывают число записей mental_model_history.'),
    @('Added Google ADK integration to connect Hindsight memory with Google ADK agents.', 'Добавлена интеграция памяти Hindsight с агентами Google ADK.'),
    @('Added Flowise integration with Hindsight memory tools.', 'Добавлена интеграция Flowise с инструментами памяти Hindsight.'),
    @('Added Fireworks AI as a batch inference provider.', 'Добавлен Fireworks AI как поставщик пакетного вывода.'),
    @('Added Roo Code integration via MCP (including rules support) to connect Roo Code with Hindsight memory.', 'Добавлена интеграция Roo Code с памятью Hindsight через MCP, включая поддержку правил.'),
    @('Added Vapi webhook integration to send voice-agent interactions into Hindsight memory.', 'Добавлена интеграция через вебхук Vapi для записи разговоров голосового агента в память Hindsight.'),
    @('Added Gemini Spark integration via MCP.', 'Добавлена интеграция Gemini Spark через MCP.'),
    @('Improved graph maintenance performance for vector search seeding (faster ANN maintenance work).', 'Ускорено обслуживание графа при подготовке векторного поиска и индекса ANN.'),
    @('Improved vector search correctness/tuning by using cosine opclass for vchord ANN and applying backend-specific tuning settings.', 'Для ANN в vchord взят косинусный класс операций и настройки по типу сервера, чтобы векторный поиск работал вернее.'),
    @('Reduced consolidation retry backoff to recover faster from transient failures.', 'Сокращена пауза между повторами консолидации для быстрого выхода из временных сбоев.'),
    @('Fixed a control-plane i18n redirect loop by pinning the Next.js version.', 'Закреплена версия Next.js, чтобы убрать цикл переадресации из-за языковых настроек Control Plane.'),
    @('Limited native ML thread pools to available CPU cores to prevent resource overuse and instability.', 'Число потоков машинного обучения ограничено доступными ядрами CPU, чтобы снизить расход ресурсов и риск сбоев.'),
    @('Fixed PostgreSQL upgrade issues for v0.7.x deployments.', 'Исправлены ошибки обновления PostgreSQL в установках v0.7.x.'),
    @('Fixed backup/restore to include previously missing tables.', 'В резервную копию и восстановление добавлены ранее пропущенные таблицы.'),
    @('Made memory consolidation more reliable under concurrency by improving scope-aware locking/dispatch and atomic submission behavior.', 'При параллельной работе консолидация памяти стала надёжнее за счёт блокировок и отправки по областям и атомарной постановки задач.'),
    @('Fixed retention of oversized documents to prevent incorrect chunk indexing and loss of full document content.', 'Исправлено сохранение больших документов: индексы частей верны, полный текст не теряется.'),
    @('Improved retain/recall robustness for unusual Unicode inputs (special-token literals and lone surrogates).', 'Сохранение и извлечение памяти лучше обрабатывают редкие символы Unicode, включая буквальные спецтокены и одиночные суррогаты.'),
    @('Fixed a race condition when inserting memory links during retain operations.', 'Исправлена гонка при добавлении связей памяти во время сохранения.'),
    @('Fixed Windows embedded daemon launch behavior to avoid opening an extra terminal tab.', 'Запуск встроенной фоновой службы в Windows больше не открывает лишнюю вкладку терминала.'),
    @('Improved embedded Postgres stop/restart reliability by updating the embedded DB dependency.', 'Обновлена зависимость встроенной базы данных для надёжной остановки и перезапуска Postgres.'),
    @('Fixed CLI memory retain timestamp handling and corrected supported fact-type values.', 'Исправлена обработка времени сохранения памяти в командной строке и список допустимых типов фактов.'),
    @('Fixed directive listing/reflect to honor tag groups so filtering behaves as expected.', 'Список директив и reflect теперь учитывают группы тегов при фильтрации.'),
    @('Fixed daemon networking to honor an explicitly configured host and port.', 'Фоновая служба теперь учитывает явно заданные адрес и порт.'),
    @('Isolated the Claude Code provider subprocess from user plugins to prevent interference and improve reliability.', 'Дочерний процесс поставщика Claude Code отделён от пользовательских плагинов, чтобы они не мешали его работе.'),
    @('Improved daemon startup reliability by waiting for health before reclaiming its port.', 'Перед возвратом порта фоновая служба ждёт успешной проверки состояния, что повышает надёжность запуска.'),
    @('Made worker retry behavior respect the configured maximum retries.', 'Повторы задач теперь соблюдают заданный предел попыток.'),
    @('Prevented retain from silently dropping memories when fact extraction fails.', 'При ошибке извлечения фактов сохранение памяти больше не пропадает без сообщения.'),
    @('Fixed control-plane auth redirects to validate return targets and honor basePath (improving security and correct routing).', 'Переадресация после входа в Control Plane теперь проверяет адрес возврата и учитывает basePath, что повышает безопасность и точность маршрута.'),
    @('Preserved raw reranker scores for providers that already return calibrated [0,1] scores.', 'Для поставщиков, которые уже возвращают оценки в диапазоне [0,1], исходные оценки переранжирования сохраняются.'),
    @('Allow configuring LLM "reasoning effort" via environment variable.', 'Усилие рассуждения языковой модели можно задать через переменную среды.'),
    @('Add per-provider HTTP timeout environment variables for reranker requests.', 'Добавлены переменные среды для времени ожидания HTTP-запросов переранжирования по поставщикам.'),
    @('Add additional Chinese locale variants in the control plane UI.', 'В интерфейсе Control Plane добавлены варианты китайского языка.'),
    @('Schedule consolidation work using bank priorities so higher-priority banks are processed first.', 'Задачи консолидации теперь идут по приоритетам банков: более важные обрабатываются первыми.'),
    @('Expose "graph_maintenance" in the control plane operations type filter dropdown.', 'В фильтре типов операций Control Plane добавлено значение "graph_maintenance".'),
    @('Make consolidation more reliable by retrying indefinitely with backoff and preventing duplicate work per bank.', 'Консолидация стала надёжнее: попытки повторяются с паузой без предела, а одинаковые задачи для банка не дублируются.'),
    @('Fixed memory corruption when retaining large documents that exceeded a single LLM call — some extracted memories could be lost. Re-retain affected documents after upgrading.', 'Исправлена порча памяти при сохранении больших документов, не вмещавшихся в один вызов модели: часть извлечённых сведений могла пропасть. После обновления сохраните затронутые документы снова.'),
    @('Improve Codex OAuth embeddings stability by adding token refresh support and follow-up fixes.', 'Добавлено обновление токена и сопутствующие правки для устойчивой работы векторов Codex OAuth.'),
    @('Fix recall recency scoring to anchor timestamps to the query time for more consistent results.', 'Оценка свежести памяти теперь привязана ко времени запроса для более ровных результатов.'),
    @('Added support for ParadeDB pg_search as a Citus-compatible BM25 search backend.', 'Добавлена поддержка ParadeDB pg_search как сервера поиска BM25, совместимого с Citus.'),
    @('Added tokenizer configuration for pg_search to better control how text is tokenized for search.', 'Добавлены настройки токенизации pg_search для точного управления разбиением текста при поиске.'),
    @('Added a new embeddings provider: ZeroEntropy.', 'Добавлен новый поставщик векторов ZeroEntropy.'),
    @('Added support for Codex OAuth-based embeddings authentication.', 'Добавлен вход через Codex OAuth для создания векторов.'),
    @('Added an API endpoint to clear mental model content.', 'Добавлена конечная точка API для очистки текста ментальной модели.'),
    @('Added targeted consolidation by observation scope to focus consolidation on specific parts of memory.', 'Консолидацию можно ограничить областью наблюдений и вести только в нужной части памяти.'),
    @('Added support for the Alibaba Qwen3 rerank model.', 'Добавлена поддержка модели переранжирования Alibaba Qwen3.'),
    @('Added Right Agent integration.', 'Добавлена интеграция Right Agent.'),
    @('Added an OpenCode Go LLM provider.', 'Добавлен поставщик языковой модели OpenCode Go.'),
    @('Added configurable BM25 language/tokenization and optional PGroonga backend for better multilingual search tuning.', 'Для поиска на разных языках добавлены настройка языка и токенизации BM25 и необязательный сервер PGroonga.'),
    @('Added an environment variable to enable API access logging (Uvicorn access logs).', 'Добавлена переменная среды для включения журнала доступа к API через Uvicorn.'),
    @('Control plane now exposes a UI action to clear the mental model.', 'В Control Plane можно очистить ментальную модель через интерфейс.'),
    @('Improved observation consolidation quality, including better handling of temporal reasoning.', 'Повышено качество консолидации наблюдений, в том числе с учётом времени.'),
    @('Control plane now supports internationalization with 8 locales.', 'Control Plane теперь поддерживает восемь языковых вариантов.'),
    @('Fixed stale outgoing links after deletions by recomputing links asynchronously.', 'После удаления устаревшие исходящие связи теперь пересчитываются асинхронно.'),
    @('Fixed Codex configuration to ignore inherited base URLs and automatically refresh OAuth access tokens.', 'Настройка Codex больше не берёт унаследованные базовые URL и автоматически обновляет токены доступа OAuth.'),
    @('Stopped sending the temperature parameter to Anthropic requests to avoid API incompatibilities.', 'Параметр temperature больше не отправляется в запросах Anthropic из-за несовместимости API.'),
    @('Prevented duplicate webhook batch deliveries for retain events.', 'Устранена повторная пакетная доставка событий сохранения через вебхук.'),
    @('Improved reliability for large retain requests by splitting oversized single items in batch retains.', 'В пакетных запросах сохранения большие отдельные записи теперь делятся на части.'),
    @('Fixed Ollama support by adding an Ollama Cloud provider and correcting authentication for cloud endpoints.', 'Исправлена поддержка Ollama: добавлен поставщик Ollama Cloud и вход для облачных адресов.'),
    @('Ensured disabled tools are not included in the agent system prompt.', 'Выключенные инструменты больше не попадают в системный запрос агента.'),
    @('Avoided retries when an embeddings provider returns invalid vector dimensions.', 'Если поставщик векторов возвращает неверную размерность, запрос больше не повторяется.'),
    @('Prevented prompt formatting errors by escaping literal braces in all user-supplied prompt fields.', 'Фигурные скобки в полях запроса пользователя теперь экранируются, чтобы форматирование не сбоило.'),
    @('Fixed issues with mental-model baseline refresh and capped history size to prevent database JSON overflow.', 'Исправлено обновление базовой ментальной модели и ограничен размер истории, чтобы JSON в базе не переполнялся.'),
    @('Enabled gzip handling to keep graph responses parseable when compressed.', 'Добавлена обработка gzip, чтобы сжатые ответы графа можно было разобрать.'),
    @('Added per-operation LLM concurrency caps to prevent overload and improve stability under parallel workloads.', 'Для каждой операции ограничено число параллельных вызовов модели, чтобы избежать перегрузки.'),
    @('Preserved tag group/triggers correctly when updating tags.', 'При обновлении тегов теперь верно сохраняются их группы и триггеры.'),
    @('Improved reranking robustness by detecting pre-normalized scores and applying rank-based normalization when needed.', 'При переранжировании распознаются уже нормированные оценки, а при нужде применяется нормировка по рангу.'),
    @('Fixed entity resolution so user-defined label entities are not fuzzy-matched incorrectly.', 'При поиске сущностей метки пользователя больше не сопоставляются неверно по нечёткому совпадению.'),
    @('Improved worker resilience by handling stale pending schema routines.', 'Рабочие процессы теперь лучше обрабатывают устаревшие ожидающие процедуры схемы.'),
    @('Fixed embedded UI startup on Windows by resolving the correct npx path before launch.', 'В Windows встроенный интерфейс теперь находит верный путь к npx до запуска.'),
    @('Improved control-plane session security by verifying signed session cookies instead of just checking presence.', 'Control Plane теперь проверяет подпись cookie сеанса, а не лишь его наличие.'),
    @('Added a configurable MCP request timeout to the Claude Code integration so long-running recall/reflect calls no longer time out at the default.', 'В интеграции Claude Code добавлено настраиваемое время ожидания MCP, чтобы долгие вызовы recall и reflect не обрывались по стандартному лимиту.'),
    @('Renamed the Agent SDK `agent_knowledge_recall` `max_results` parameter to `max_tokens` and raised the default from 10 to 1024 so default-config users get useful recall results.', 'В Agent SDK параметр `max_results` инструмента `agent_knowledge_recall` переименован в `max_tokens`; значение по умолчанию выросло с 10 до 1024 для полезного результата поиска.'),
    @('Applied the same `max_results`→`max_tokens` rename to the Claude Code MCP plugin so both integrations stay in sync.', 'В плагине MCP для Claude Code параметр `max_results` также переименован в `max_tokens`, чтобы обе интеграции совпадали.'),
    @('Bumped vulnerable dependencies across the stack to address GitHub-reported CVEs — including litellm to ≥1.83.14, urllib3 to 2.7.0, and additional high/critical pip and npm packages.', 'Обновлены уязвимые зависимости по отчётам GitHub CVE: litellm до ≥1.83.14, urllib3 до 2.7.0 и другие пакеты pip и npm с серьёзными уязвимостями.'),
    @('Fixed the CLI “memory retain” timestamp/Event Date option so the provided timestamp is actually sent to the API.', 'Параметр времени/Event Date команды “memory retain” теперь передаёт заданное время в API.'),
    @('Repaired a database migration issue affecting mental model subtype data at the current schema head.', 'Исправлена миграция базы данных, затронувшая подтипы ментальной модели в текущей версии схемы.'),
    @('Improved migration robustness by handling transient database OID errors during the embedding-dimension migration.', 'При миграции размерности векторов теперь обрабатываются временные ошибки OID базы данных.'),
    @('Fixed Claude Code knowledge `get_page` calls to request `detail=content` and avoid tool-result spillover so full page content returns reliably.', 'Вызовы `get_page` в знаниях Claude Code теперь запрашивают `detail=content` и не смешивают результаты инструментов, поэтому полный текст страницы возвращается надёжно.'),
    @('Applied the same `agent_knowledge_get_page` `detail=content` fix to the Agent SDK so SDK callers also receive full page content.', 'Та же правка `detail=content` внесена в `agent_knowledge_get_page` Agent SDK, чтобы клиенты тоже получали полный текст страницы.'),
    @("Aligned the Paperclip integration with Paperclip's actual event payload shape, restoring correct fact extraction from incoming events.", 'Интеграция Paperclip приведена к реальному формату событий, чтобы факты снова верно извлекались из входящих данных.'),
    @('Added AlloyDB ScaNN vector index support, providing a high-performance vector index option for AlloyDB deployments', 'Добавлена поддержка векторного индекса AlloyDB ScaNN для быстрого поиска в установках AlloyDB'),
    @('Added map-type entity labels so entity extraction can produce structured groups (e.g. address fields) instead of flat strings', 'Добавлены метки сущностей типа map: при извлечении можно получать группы полей, например адрес, вместо плоской строки'),
    @('Added z.ai (智谱) as a first-class LLM provider with a free-tier-friendly default model', 'Добавлен поставщик языковых моделей z.ai (智谱) с моделью по умолчанию, доступной на бесплатном уровне'),
    @('Added a litellmrouter provider that lets the API call multiple LLM endpoints with automatic fallback chains', 'Добавлен поставщик litellmrouter: API может обращаться к нескольким адресам моделей с автоматической цепочкой резервных вариантов'),
    @('Added an optional read-only database backend for recall queries, letting recall traffic go to a replica while writes stay on the primary', 'Для поиска памяти добавлена необязательная база только для чтения: запросы идут на реплику, а запись остаётся на основной базе'),
    @('Added optional access-key login to the Control Plane for protecting the admin UI without a full SSO setup', 'Для защиты интерфейса Control Plane добавлен необязательный вход по ключу без полной настройки единого входа'),
    @('Added a `--strategy` flag to `memory retain-files` in the CLI for selecting how files are split before retention', 'В команде `memory retain-files` добавлен флаг `--strategy` для выбора способа деления файлов перед сохранением'),
    @('Bank dropdown in the Control Plane now shows per-bank memory counts to make bank selection easier', 'В списке банков Control Plane теперь видно число записей памяти в каждом банке'),
    @('Worker progress-stats fanout is now scoped to schemas with pending work, eliminating wasted polling on idle tenants', 'Сбор статистики прогресса рабочих процессов теперь охватывает лишь схемы с ожидающими задачами, не опрашивая простаивающих арендаторов'),
    @('Fixed fact extraction reliability by removing multiplicative retry layers that could turn one transient LLM failure into many', 'Убраны вложенные повторы, из-за которых один временный сбой модели вызывал много новых попыток извлечения фактов'),
    @('Fixed reflect to read document metadata from the original retain parameters so reflect outputs include the right document context', 'Reflect теперь берёт метаданные документа из исходных параметров сохранения, чтобы ответ содержал верный контекст'),
    @('Failed batch_retain operations now propagate the child error_message to the parent, so failures surface a meaningful reason instead of a generic error', 'При сбое batch_retain дочерняя ошибка error_message передаётся основной операции, чтобы вместо общей ошибки показывать её причину'),
    @('Fixed macOS daemon mode by replacing os.fork() with subprocess.Popen, restoring compatibility with PyTorch MPS', 'В фоновой службе macOS вызов os.fork() заменён на subprocess.Popen для совместимости с PyTorch MPS'),
    @('Hardened Control Plane access-key authentication and improved login UX (clearer errors, redirect handling)', 'Усилен вход в Control Plane по ключу; ошибки стали яснее, а переадресация работает лучше'),
    @('Reduced retain memory pressure by clearing content references after use, helping long-running workers avoid OOM on large batches', 'После сохранения ссылки на текст очищаются, чтобы долгие рабочие процессы не исчерпывали память на больших партиях'),
    @('Fixed Docker image to chmod 755 /home/hindsight so containers run cleanly with --user UID:GID overrides', 'В образе Docker для /home/hindsight заданы права 755, чтобы контейнер работал и с --user UID:GID'),
    @('Hard-pinned meta packages (hindsight-api, hindsight-all, hindsight-all-slim) to matching hindsight-api-slim, preventing stale slim installs after upgrade', 'Мета-пакеты hindsight-api, hindsight-all и hindsight-all-slim жёстко привязаны к той же версии hindsight-api-slim, чтобы после обновления не оставалась старая slim-версия'),
    @("Worker now probes pg_proc before calling the optional schemas_with_pending_work() function, so older databases without it don't crash the worker", 'Перед вызовом необязательной функции schemas_with_pending_work() рабочий процесс проверяет pg_proc, чтобы старые базы без неё не вызывали сбой'),
    @('TypeScript client now derives CLIENT_VERSION via tsup define so the published package version is always reported correctly', 'Клиент TypeScript теперь получает CLIENT_VERSION через tsup define, чтобы всегда сообщать верную версию выпущенного пакета'),
    @('Added Dify integration providing Hindsight memory tools inside Dify workflows.', 'Добавлена интеграция Dify с инструментами памяти Hindsight в процессах Dify.'),
    @('Added n8n community node package for using Hindsight memory in n8n automations.', 'Добавлен пакет узла сообщества n8n для работы с памятью Hindsight в автоматизации n8n.'),
    @('Added SmolAgents integration providing Hindsight memory tools for SmolAgents-based agents.', 'Добавлена интеграция SmolAgents с инструментами памяти Hindsight для агентов на её базе.'),
    @('Added AWS Bedrock AgentCore Runtime integration (hindsight-agentcore).', 'Добавлена интеграция AWS Bedrock AgentCore Runtime (hindsight-agentcore).'),
    @('Added an Oracle Database backend option for enterprise storage.', 'Для корпоративного хранения добавлена поддержка базы Oracle.'),
    @('Added the ability to cancel long-running async operations.', 'Долгие асинхронные операции теперь можно отменять.'),
    @('Typescript client now supports AbortSignal across all methods for request cancellation.', 'Клиент TypeScript теперь поддерживает AbortSignal во всех методах для отмены запросов.'),
    @('Python client now exposes retain_async via retain()/aretain() for async memory retention flows.', 'Клиент Python теперь даёт доступ к retain_async через retain()/aretain() для асинхронного сохранения памяти.'),
    @('Anthropic provider now supports environment-configurable max retries and default headers.', 'Для поставщика Anthropic через переменные среды можно задать предел повторов и заголовки по умолчанию.'),
    @('Memories timeseries stats can now be grouped by different time fields (time_field toggle).', 'Статистику памяти по времени можно группировать по разным временным полям (переключатель time_field).'),
    @('Improved database performance for observation reads by reducing overhead and making reads backend-aware.', 'Чтение наблюдений из базы ускорено за счёт меньших накладных расходов и учёта типа базы.'),
    @('Fixed search ranking by correcting BM25 score direction for the vchord backend.', 'Исправлен порядок результатов поиска: оценка BM25 для vchord теперь направлена верно.'),
    @('Recall now correctly inherits observation entities through source_memory_ids, improving entity continuity across related memories.', 'При извлечении память теперь наследует сущности наблюдений через source_memory_ids, сохраняя связь между записями.'),
    @('Entity co-occurrence timestamps now use the event date instead of the ingestion time, improving timeline accuracy.', 'Время совместного появления сущностей теперь берётся по дате события, а не загрузки, для более точной хронологии.'),
    @('Daemon mode now respects configured host settings (CLI --host and HINDSIGHT_API_HOST).', 'Фоновая служба теперь учитывает заданный адрес (CLI --host и HINDSIGHT_API_HOST).'),
    @('Webhooks are now processed tenant-aware to prevent cross-tenant routing issues.', 'Вебхуки теперь обрабатываются с учётом арендатора, чтобы не смешивать их маршруты.'),
    @('API per-document graph and counts now include observations, improving completeness of document-level views.', 'Граф и счётчики API для документа теперь включают наблюдения.'),
    @('Improved compatibility with OpenAI-compatible providers by hardening JSON response parsing and handling null content.', 'Улучшена совместимость с поставщиками API в формате OpenAI: JSON-ответы и пустой текст обрабатываются надёжнее.'),
    @("Fixed Windows worker startup by handling platforms that don't implement add_signal_handler.", 'Исправлен запуск рабочего процесса в Windows и других системах без add_signal_handler.'),
    @('Retain/batch retain reliability improved by fixing transactional atomicity, recovery checkpoint scoping, and a cascade deadlock risk.', 'Сохранение памяти и пакетное сохранение стали надёжнее: исправлены атомарность транзакций, область контрольных точек восстановления и риск цепной блокировки.'),
    @('Typescript client now exposes previously missing recall/reflect parameters.', 'Клиент TypeScript теперь даёт доступ к ранее отсутствовавшим параметрам recall и reflect.'),
    @('MCP recall tool now exposes tag_groups so recalls can be filtered/grouped by tag groups.', 'Инструмент recall в MCP теперь принимает tag_groups для поиска и группировки по группам тегов.'),
    @('Embed/daemon startup reliability improved (script path resolution, correct extras when spawning API, and safer subprocess output handling).', 'Запуск встроенного режима и фоновой службы стал надёжнее: исправлены пути скриптов, доппакеты при запуске API и обработка вывода дочерних процессов.'),
    @('Configuration logging now redacts database URLs to avoid leaking credentials in logs.', 'В журналах настройки адреса баз данных теперь скрыты, чтобы не раскрывать учётные данные.'),
    @('Fixed support for OpenAI-compatible embedding dimensions by allowing provider-specific parameters.', 'Для размерности векторов API в формате OpenAI теперь можно задавать параметры поставщика.'),
    @('Reverted the JSON schema simplification introduced in 0.5.5 (`5b1c3486`). The change inlined `$ref`/`$defs` into a large blob that caused some LLMs (notably GPT-4o-mini in soft-enforcement mode) to echo the schema structure instead of producing valid responses, resulting in 0 facts extracted during retain. **If you are on 0.5.5, upgrade to 0.5.6 immediately.**', 'Отменено упрощение схемы JSON из версии 0.5.5 (`5b1c3486`). Оно разворачивало `$ref`/`$defs` в большой блок, из-за чего некоторые модели, в том числе GPT-4o-mini при мягком соблюдении схемы, повторяли структуру схемы вместо верного ответа. При сохранении извлекалось 0 фактов. **Если у вас версия 0.5.5, сразу обновитесь до 0.5.6.**'),
    @('**0.5.5 contains a regression that can cause 0 facts to be extracted during retain.**', '**В версии 0.5.5 есть ошибка, из-за которой при сохранении может извлекаться 0 фактов.**'),
    @('The JSON schema simplification change (`5b1c3486`) was reverted in', 'Упрощение схемы JSON (`5b1c3486`) отменено в'),
    @('Please upgrade to 0.5.6.', 'Обновитесь до 0.5.6.'),
    @('Added a new LlamaParse file parser, using the LlamaIndex Cloud parsing API to convert documents (PDF, DOCX, etc.) to markdown before retain.', 'Добавлен разбор файлов LlamaParse: перед сохранением он переводит документы PDF, DOCX и другие в Markdown через API LlamaIndex Cloud.'),
    @('Added a new Mental Models list view and tag filtering from mental models.', 'Добавлен список ментальных моделей и фильтр по их тегам.'),
    @('Added Pipecat voice AI pipeline integration so voice agents can use Hindsight long-term memory.', 'Добавлена интеграция голосового конвейера Pipecat с долговременной памятью Hindsight.'),
    @('Added an option to force IPv4 for Gemini embeddings to improve compatibility in restricted network environments.', 'Для векторов Gemini можно принудительно включить IPv4 при работе в сетях с ограничениями.'),
    @('Added support to control Cohere embedding output dimensions via configuration.', 'Размерность векторов Cohere теперь можно задать в настройках.'),
    @('Added a new Document Chunks API plus document reprocessing and a richer document detail experience in the UI.', 'Добавлен API частей документа, повторная обработка документов и более подробный экран документа.'),
    @('Added an exclude_parents filter for list operations to better control what results are returned.', 'В списках добавлен фильтр exclude_parents для выбора возвращаемых записей.'),
    @('Operation responses now include retry information (retry count and next retry time).', 'Ответы операций теперь содержат число повторов и время следующей попытки.'),
    @('Retain results now include processed content token counts for better usage/throughput visibility.', 'Результаты сохранения памяти теперь показывают число обработанных токенов для оценки расхода и скорости.'),
    @('Added full Windows support for the embedded runtime and improved how the local API is discovered/launched.', 'Добавлена полная поддержка Windows для встроенного режима; поиск и запуск локального API улучшены.'),
    @('Operation status reporting now includes processing and cancelled states across the API and UI.', 'Статус операций в API и интерфейсе теперь включает состояния обработки и отмены.'),
    @('Workers can reserve per-operation slots when claiming tasks, improving fairness and throughput under load.', 'Рабочие процессы могут резервировать места для каждого типа операций при взятии задач, что лучше делит нагрузку.'),
    @('PostgreSQL connections now support a configurable statement timeout to prevent runaway queries.', 'Для соединений PostgreSQL можно задать время ожидания запроса, чтобы долгие запросы не зависали.'),
    @('Improved LLM interoperability by simplifying JSON schemas and avoiding problematic tool-choice defaults.', 'Улучшена совместимость моделей за счёт упрощения схем JSON и отказа от проблемного выбора инструментов по умолчанию.'),
    @('Reverted in 0.5.6 — caused 0 facts extracted with some LLMs.', 'Отменено в 0.5.6 — некоторые модели извлекали 0 фактов.'),
    @('Worker scheduling no longer allows child tasks to block parent execution.', 'Дочерние задачи больше не блокируют основные при планировании.'),
    @('Fixed DeepSeek compatibility issues (including tool-calling quirks) and added it as a first-class LLM provider.', 'Исправлена совместимость с DeepSeek, включая вызовы инструментов; он добавлен как полноценный поставщик моделей.'),
    @('Fixed Amazon Bedrock Converse compatibility by adjusting how causal relations are represented.', 'Для совместимости с Amazon Bedrock Converse изменено представление причинных связей.'),
    @('GET /banks/\{bank_id\}/profile no longer creates a bank as a side effect.', 'GET /banks/\{bank_id\}/profile больше не создаёт банк как побочный эффект.'),
    @('Reduced memory fan-out during consolidation recall to prevent excessive retrieval and improve stability.', 'При поиске памяти для консолидации снижено разветвление запросов, чтобы не извлекать лишнее.'),
    @('External PostgreSQL connection strings now accept asyncpg-style URLs.', 'Строки подключения к внешнему PostgreSQL теперь принимают адреса в формате asyncpg.'),
    @('Timeseries stats buckets now return timezone-aware ISO timestamps.', 'Интервалы статистики по времени теперь возвращают метки ISO с часовым поясом.'),
    @('Fixed conversation storage when using streaming LLM responses via LiteLLM.', 'Исправлено хранение бесед при потоковых ответах модели через LiteLLM.'),
    @('Removed the MCP delete_memory tool to close an authorization-bypass vulnerability.', 'Инструмент MCP delete_memory удалён из-за уязвимости, позволявшей обойти проверку прав.'),
    @('First-time UI launch no longer requires manual confirmation to install the control plane.', 'При первом запуске интерфейса больше не нужно вручную подтверждать установку Control Plane.'),
    @('Delta mental model refresh now scopes recall to memories created since the last refresh, making updates faster and more accurate.', 'При частичном обновлении ментальной модели поиск ограничен памятью, созданной после прошлого обновления, что ускоряет работу и повышает точность.'),
    @('OpenAI-compatible embedding providers now support configurable batch sizes for better throughput.', 'Для поставщиков векторов с API в формате OpenAI можно настроить размер партии для ускорения обработки.'),
    @('Embedded daemon now includes a liveness check that auto-recovers from crashes.', 'Встроенная фоновая служба теперь проверяет своё состояние и восстанавливается после сбоя.'),
    @('Disable daemon idle timeout by default so embedded instances stay alive between requests.', 'Время ожидания простоя фоновой службы по умолчанию отключено, чтобы встроенные экземпляры не завершались между запросами.'),
    @('Add `{user_id}` template variable for retainTags in the Claude Code integration.', 'В интеграции Claude Code в retainTags добавлена переменная шаблона `{user_id}`.'),
    @('New `decommission-workers` and `worker-status` admin CLI commands for managing worker fleets.', 'Добавлены команды администратора `decommission-workers` и `worker-status` для управления рабочими процессами.'),
    @('Fix duplicate memory units caused by chunk index scrambling during concurrent upserts.', 'Устранено дублирование элементов памяти из-за неверного порядка индексов частей при параллельном обновлении.'),
    @('Prevent directive content from leaking into reflect answers on empty banks.', 'Текст директив больше не попадает в ответы reflect для пустых банков.'),
    @('Honor the reflect_mission identity framing in the prompt builder so agent personality works correctly.', 'Сборщик запросов теперь учитывает описание роли reflect_mission, чтобы характер агента задавался верно.'),
    @('Allow reflect-specific LLM configuration when the default LLM provider is disabled.', 'Для reflect теперь можно задать отдельную модель, даже если основной поставщик моделей выключен.'),
    @('Preserve document `created_at` timestamp across upsert and add UI edit flow for documents.', 'При обновлении документа сохраняется `created_at`; в интерфейсе добавлена правка документов.'),
    @('Fix `ensure_ascii=False` in json.dumps for LLM prompts so non-Latin text is preserved.', 'Для запросов к модели исправлено применение `ensure_ascii=False` в json.dumps, чтобы текст вне латиницы сохранялся.'),
    @('Route `update_bank` through the config resolver with generic config_updates.', 'Вызов `update_bank` теперь проходит через обработчик настроек с общим полем config_updates.'),
    @('Workers now scan for active schemas before claiming tasks, preventing work on decommissioned tenants.', 'Перед взятием задач рабочие процессы проверяют активные схемы и не работают с отключёнными арендаторами.'),
    @('Pass DeferOperation through MemoryEngine.execute_task so extensions can requeue work.', 'Исключение DeferOperation теперь проходит через MemoryEngine.execute_task, чтобы расширения могли снова поставить задачу в очередь.'),
    @('Downgrade LLM verify_connection failure to a warning instead of crashing on startup.', 'Ошибка LLM verify_connection теперь выдаёт предупреждение, а не срывает запуск.'),
    @('Fix `items_count` in list_operations response to populate from result_metadata.', 'Поле `items_count` ответа list_operations теперь заполняется из result_metadata.'),
    @('Align AI SDK ReflectBasedOn types with the OpenAPI spec.', 'Типы ReflectBasedOn в AI SDK приведены к спецификации OpenAPI.'),
    @('Fix database migration path by merging divergent Alembic heads for v0.5.3.', 'Для версии 0.5.3 объединены разошедшиеся ветки Alembic, чтобы миграция базы шла верно.'),
    @('Lower OpenCode retainEveryNTurns default from 10 to 3 for more frequent memory saves.', 'В OpenCode значение retainEveryNTurns по умолчанию снижено с 10 до 3 для более частого сохранения памяти.'),
    @('Add a setting to limit how many memories can be consolidated per round, helping control consolidation workload and cost.', 'Добавлен лимит числа записей памяти за один цикл консолидации для контроля нагрузки и расходов.'),
    @('Add integration with the OpenAI Agents SDK.', 'Добавлена интеграция с OpenAI Agents SDK.'),
    @('Improve mental model refresh and updates with structured operations and cleaner observation handling on upsert.', 'Обновление ментальной модели улучшено за счёт структурированных операций и более точной обработки наблюдений при записи.'),
    @('Allow extensions to requeue work by throwing a DeferOperation exception from worker operations.', 'Расширения могут снова ставить задачи в очередь через исключение DeferOperation в рабочей операции.'),
    @('Make recall budget mapping configurable per memory bank.', 'Для каждого банка памяти можно настроить распределение бюджета поиска.'),
    @('Control plane now shows failed consolidation counts with a drilldown to investigate issues.', 'Control Plane теперь показывает число сбоев консолидации с переходом к деталям.'),
    @('Add mental-model staleness signals and a refreshed UI/experience for reviewing model history and snapshots.', 'Добавлены признаки устаревания ментальной модели и обновлённый просмотр её истории и снимков.'),
    @('Replace the embedded Paperclip library with the Paperclip plugin for more flexible integrations.', 'Встроенная библиотека Paperclip заменена плагином для более гибкой интеграции.'),
    @('JSON logs can now include tenant information and support a configurable allowlist for what gets logged.', 'JSON-журналы теперь могут содержать сведения об арендаторе; состав записываемых полей задаётся списком разрешённых.'),
    @('CLI now supports named connection profiles (via -p/--profile) for easier switching between environments.', 'Командная строка поддерживает именованные профили подключения через -p/--profile для быстрого выбора среды.'),
    @('Reduce the default number of retries for LLM calls to fail faster when providers are erroring or unavailable.', 'Число повторов вызова модели по умолчанию уменьшено, чтобы быстрее сообщать о сбое или недоступности поставщика.'),
    @('Make reranker failures easier to diagnose and add a configurable timeout for the TEI reranker.', 'Ошибки переранжирования теперь проще искать; для TEI можно задать время ожидания.'),
    @('Fix crashes when using Jina MLX on Metal GPUs by serializing GPU operations.', 'Операции GPU при работе Jina MLX на Metal теперь идут по очереди, чтобы избежать сбоев.'),
    @('Fix database migration path so upgrades from v0.4.22 to v0.5.x work correctly.', 'Исправлены миграции базы при обновлении с v0.4.22 до v0.5.x.'),
    @('Prevent orphaned observations if a source memory is deleted during consolidation.', 'При удалении исходной записи памяти во время консолидации наблюдения больше не остаются без связи.'),
    @('Fix Ollama requests by explicitly disabling "think" mode in the native call payload.', 'В запросах Ollama режим "think" теперь явно выключен.'),
    @('Fix file retain uploads and prevent orphaned retained files.', 'Исправлена загрузка файлов для сохранения памяти; файлы больше не остаются без связи.'),
    @('Fix file retain API to correctly accept and map a provided "timestamp" field.', 'API сохранения файлов теперь верно принимает и передаёт поле "timestamp".'),
    @('Improve fairness across tenants when workers claim tasks, reducing the chance of noisy tenants starving others.', 'Рабочие процессы справедливее делят задачи между арендаторами, чтобы один активный арендатор не задерживал остальных.'),
    @('Ensure the mental model max_tokens setting is respected during refresh/reflect operations.', 'При обновлении ментальной модели и reflect теперь соблюдается её параметр max_tokens.'),
    @('Fix control-plane links by properly encoding bank IDs in URLs end-to-end.', 'В ссылках Control Plane ID банков теперь верно кодируются в URL.'),
    @('Make task submission idempotent when a payload is already set, preventing duplicate/failed submissions.', 'Повторная отправка задачи с уже заданными данными теперь безопасна и не создаёт дублей или ошибок.'),
    @('Added a co-occurrence graph view for exploring entity relationships in the control plane.', 'В Control Plane добавлен граф совместного появления сущностей для изучения их связей.'),
    @('Added recall controls to the mental model trigger API/CLI so you can tune what gets recalled during runs.', 'В API и командной строке запуска ментальной модели добавлены настройки извлечения памяти.'),
    @('Async operations now expose task payload details and associated document IDs for better observability and debugging.', 'Асинхронные операции теперь показывают данные задачи и ID связанных документов для контроля и отладки.'),
    @('Revamped the control plane bank statistics view for clearer insights.', 'Обновлён экран статистики банка в Control Plane.'),
    @('Clients now send an identifying User-Agent header on all HTTP requests for easier server-side diagnostics.', 'Клиенты теперь отправляют User-Agent во всех HTTP-запросах, чтобы упростить поиск ошибок на сервере.'),
    @('Fixed consolidation retry budget handling so retries are correctly applied at the LLM call site.', 'Лимит повторов консолидации теперь верно применяется при вызове модели.'),
    @("Fixed a crash during retain when embeddings and extracted facts counts didn’t match.", 'Исправлен сбой сохранения памяти, когда число векторов и извлечённых фактов не совпадало.'),
    @('Improved embedded mode cleanup stability by adding a timeout when acquiring the cleanup lock (prevents hangs).', 'При очистке встроенного режима добавлено время ожидания блокировки, чтобы процесс не зависал.'),
    @('OpenClaw plugins now reliably register agent hooks on every entry invocation.', 'Плагины OpenClaw теперь надёжно регистрируют хуки агента при каждом вызове точки входа.'),
    @('TypeScript SDK now re-exports BankTemplate types from the package root for simpler imports.', 'SDK TypeScript теперь экспортирует типы BankTemplate из корня пакета для простого импорта.'),
    @('Bank template configuration validation was aligned with configurable fields to prevent invalid/ignored settings.', 'Проверка шаблона банка теперь учитывает настраиваемые поля, чтобы неверные параметры не проходили и не игнорировались.'),
    @('OpenClaw now reads configuration from plugin config instead of environment variables.', 'OpenClaw теперь читает настройки из плагина, а не из переменных среды.'),
    @('Added SiliconFlow as a supported reranker provider.', 'Добавлена поддержка SiliconFlow как поставщика переранжирования.'),
    @('Added an interactive OpenClaw setup wizard with Cloud / API / Embedded modes.', 'Добавлен интерактивный мастер настройки OpenClaw с режимами Cloud, API и Embedded.'),
    @('Added a config-aware CLI to backfill OpenClaw history.', 'Добавлена командная строка для загрузки прошлых данных OpenClaw с учётом настроек.'),
    @('Added OpenClaw session pattern filtering to ignore or treat sessions as stateless.', 'Добавлена фильтрация сеансов OpenClaw по шаблону: их можно пропускать или считать не имеющими состояния.'),
    @('Added a Cloudflare OAuth proxy integration option for self-hosted Hindsight.', 'Для собственного сервера Hindsight добавлено подключение через прокси Cloudflare OAuth.'),
    @('Expanded the CLI to cover all OpenAPI endpoints and request-body parameters.', 'Командная строка теперь охватывает все конечные точки OpenAPI и параметры тела запроса.'),
    @('Added a default bank template environment variable (HINDSIGHT_API_DEFAULT_BANK_TEMPLATE).', 'Добавлена переменная среды HINDSIGHT_API_DEFAULT_BANK_TEMPLATE для шаблона банка по умолчанию.'),
    @('Added a daemon lifecycle package (@vectorize-io/hindsight-all) to simplify running the all-in-one daemon.', 'Добавлен пакет @vectorize-io/hindsight-all для управления жизненным циклом общей фоновой службы.'),
    @('Added recallTags and recallTagsMatch configuration options to control which tagged memories are recalled.', 'Настройки recallTags и recallTagsMatch позволяют выбирать, какую память с тегами извлекать.'),
    @('Improved OpenClaw reliability with more resilient startup behavior and richer retain metadata.', 'Запуск OpenClaw стал устойчивее, а метаданные сохранённой памяти — полнее.'),
    @('OpenClaw setup wizard now prompts for the token value (not the env var name).', 'Мастер настройки OpenClaw теперь просит значение токена, а не имя переменной среды.'),
    @('Fixed embedded mode daemon start/stop race that could terminate healthy daemons.', 'Исправлена гонка запуска и остановки фоновой службы во встроенном режиме, из-за которой исправная служба могла завершиться.'),
    @('Fixed reranker initialization issues to show real import errors and avoid a Transformers 5.x race in jina-mlx.', 'При запуске переранжирования теперь показываются исходные ошибки импорта и устранена гонка Transformers 5.x в jina-mlx.'),
    @('Fixed worker consolidation slot accounting to respect the configured maximum concurrency.', 'Учёт мест консолидации у рабочих процессов теперь соблюдает заданный предел параллельности.'),
    @('Improved CLI API error output by including the HTTP response body.', 'Ошибки API в командной строке теперь включают тело HTTP-ответа.'),
    @('Fixed CLI memory listing showing "[UNKNOWN]" for fact types.', 'Список памяти в командной строке больше не показывает "[UNKNOWN]" для типов фактов.'),
    @('Fixed recall ranking so RRF ordering is preserved when the reranker is configured as a passthrough.', 'При отключённом переранжировании результаты поиска сохраняют порядок RRF.'),
    @('Fixed retain chunk insertion to be idempotent and avoid repeated retries on integrity errors.', 'Повторная вставка частей памяти теперь безопасна и не запускает лишние попытки при ошибке целостности.'),
    @('Fixed retain ANN seed temp table creation to run inside a transaction for better reliability.', 'Временная таблица для подготовки ANN при сохранении теперь создаётся внутри транзакции.'),
    @('Fixed LLM requests to use the correct max token parameter for reasoning models and Azure OpenAI.', 'Запросы к моделям рассуждения и Azure OpenAI теперь передают верный параметр предела токенов.'),
    @('Removed BFS and MPFP graph retrieval strategies. LinkExpansionRetriever is now the sole graph retrieval algorithm, offering simpler, faster, and more accurate results.', 'Стратегии поиска по графу BFS и MPFP удалены. Остался LinkExpansionRetriever: он проще, быстрее и точнее.'),
    @('Dropped the `hindsight-hermes` integration package.', 'Пакет интеграции `hindsight-hermes` удалён.'),
    @('Built-in llama.cpp LLM provider for fully local inference without external API calls.', 'Добавлен встроенный поставщик llama.cpp для полностью локальной работы модели без внешнего API.'),
    @('Retain `update_mode=''append''` for concatenating new content onto an existing document instead of replacing it.', 'Режим `update_mode=''append''` дописывает новый текст к документу вместо замены.'),
    @('OpenRouter support for LLM, embeddings, and reranking.', 'Добавлена поддержка OpenRouter для языковых моделей, векторов и переранжирования.'),
    @("Bank template import/export with Template Hub — export a bank's configuration, mental models, and directives as a reusable manifest, then import into other banks.", 'Через Template Hub можно экспортировать настройки банка, ментальные модели и директивы как повторно применимый манифест, а затем импортировать в другие банки.'),
    @('Constellation view in the Control Plane — interactive, zoomable canvas visualization of entity relationship graphs with heat-gradient coloring and dark mode support.', 'В Control Plane добавлен вид «Созвездие»: интерактивный масштабируемый граф связей сущностей с цветом по плотности и тёмной темой.'),
    @('Added `detail` parameter to list/get mental model endpoints for controlling response verbosity.', 'В конечные точки списка и получения ментальных моделей добавлен параметр `detail` для выбора объёма ответа.'),
    @('Added AutoGen integration (`hindsight-autogen`) for persistent long-term memory in AutoGen agents.', 'Добавлена интеграция AutoGen (`hindsight-autogen`) с долговременной памятью для агентов.'),
    @('Added Paperclip integration (`@vectorize-io/hindsight-paperclip`) with Express middleware and process adapter modes for stateless agent memory.', 'Добавлена интеграция Paperclip (`@vectorize-io/hindsight-paperclip`) с промежуточным слоем Express и адаптером процесса для памяти агентов без состояния.'),
    @('Added OpenCode persistent memory plugin for the OpenCode editor.', 'Добавлен плагин долговременной памяти для редактора OpenCode.'),
    @('OpenClaw JSONL-backed retain queue for external API resilience — buffers retain calls locally when the API is unreachable.', 'Очередь сохранения OpenClaw на базе JSONL хранит вызовы локально, пока внешний API недоступен.'),
    @('OpenClaw now supports `bankId` for static bank configurations.', 'OpenClaw теперь поддерживает `bankId` для статических банков.'),
    @('Added Google embeddings and reranker provider support.', 'Добавлена поддержка Google как поставщика векторов и переранжирования.'),
    @('Added persistent volume support in Helm chart for local model cache.', 'В Helm-чарте добавлен постоянный том для кэша локальной модели.'),
    @('MCP server now includes a `sync_retain` tool and validates UUID inputs.', 'Сервер MCP теперь содержит инструмент `sync_retain` и проверяет UUID во входных данных.'),
    @('Recall combined scoring now includes `proof_count` boost for better ranking.', 'Общая оценка при поиске памяти теперь учитывает усиление `proof_count` для лучшего порядка результатов.'),
    @('3-phase retain pipeline restructures memory ingestion into pre-resolve, insert, and post-link phases, dramatically improving throughput under concurrent load by removing slow reads from write transactions.', 'Трёхэтапное сохранение памяти делит загрузку на поиск связей, вставку и связывание после записи. Медленное чтение убрано из транзакций записи, поэтому параллельная обработка быстрее.'),
    @('Recall entity graph expansion now caps per-entity fanout and includes a timeout fallback, preventing slow queries on banks with high-fanout entities.', 'При обходе графа для поиска памяти ограничено число связей каждой сущности и добавлен запасной вариант по времени ожидания, чтобы сложные банки не тормозили.'),
    @('Fact serialization in think-prompt now includes `occurred_end` and `mentioned_at` for richer temporal context.', 'В запросе для рассуждения факты теперь содержат `occurred_end` и `mentioned_at` для полного временного контекста.'),
    @('Consolidation observation quality improved with structured processing rules.', 'Структурированные правила обработки повысили качество наблюдений при консолидации.'),
    @('LiteLLM SDK embeddings `encoding_format` is now configurable instead of hardcoded.', 'Параметр `encoding_format` для векторов LiteLLM SDK теперь настраивается.'),
    @('Fixed out-of-range `content_index` crash in recall result mapping.', 'Исправлен сбой поиска памяти при `content_index` вне допустимого диапазона.'),
    @('Experience fact types are now preserved correctly during normalization.', 'Типы фактов опыта теперь верно сохраняются при нормализации.'),
    @('Clear memories endpoint no longer deletes the bank profile.', 'Очистка памяти через API больше не удаляет профиль банка.'),
    @('Embedding daemon clears stale processes on the port before starting.', 'Служба создания векторов перед запуском удаляет старые процессы на своём порту.'),
    @('Per-bank vector index migration now respects vector extension configuration.', 'Миграция векторного индекса по банкам теперь учитывает настройки векторного расширения.'),
    @('Timeline group sort uses numeric date comparison instead of locale string comparison.', 'Группы хронологии теперь сортируются по числовым датам, а не по строкам с учётом локали.'),
    @('Resolved 25 test regressions from the streaming retain pipeline.', 'Исправлены 25 ошибок тестов после перехода на потоковое сохранение памяти.'),
    @('MCP server now auto-coerces string-encoded JSON in tool arguments.', 'Сервер MCP теперь автоматически преобразует JSON-строки в аргументах инструментов.'),
    @('Entity labels structure is now validated on PATCH to prevent invalid configurations.', 'При PATCH теперь проверяется структура меток сущностей, чтобы не сохранять неверные настройки.'),
    @('Fixed `bank_id` metric label to be opt-in, preventing OTel memory leak.', 'Метка метрики `bank_id` теперь включается отдельно, чтобы избежать утечки памяти OTel.'),
    @('Fixed `max_tokens` handling for OpenAI-compatible endpoints with custom base URLs.', 'Исправлена обработка `max_tokens` для адресов API в формате OpenAI с заданным базовым URL.'),
    @('Fixed `event_date` AttributeError when date is None in fact extraction.', 'Исправлена ошибка AttributeError для `event_date`, когда дата при извлечении фактов равна None.'),
    @('Query analyzer now handles dateparser internal crashes gracefully.', 'Анализатор запросов теперь обрабатывает внутренние сбои dateparser без аварийного завершения.'),
    @('Embedding profile `.env` overwrite skipped when config has no Hindsight keys.', 'Файл `.env` профиля векторов больше не перезаписывается, если в настройках нет ключей Hindsight.'),
    @('Windows compatibility fix for hindsight-embed.', 'Исправлена совместимость hindsight-embed с Windows.'),
    @('Addressed critical and high severity security vulnerabilities in dependencies.', 'Устранены критические и серьёзные уязвимости в зависимостях.'),
    @('API now supports passing custom LLM request parameters via the HINDSIGHT_API_LLM_EXTRA_BODY configuration.', 'Через HINDSIGHT_API_LLM_EXTRA_BODY API теперь принимает свои параметры запросов к языковой модели.'),
    @('Document metadata is now exposed through the API and control plane.', 'Метаданные документов теперь доступны в API и Control Plane.'),
    @('Added a /code-review skill for automated code quality checks against project standards.', 'Добавлен навык /code-review для автоматической проверки кода по правилам проекта.'),
    @('ZeroEntropy reranker now supports a configurable base URL.', 'Для переранжирования ZeroEntropy теперь можно задать базовый URL.'),
    @('Codex can now retain structured tool calls from rollout files.', 'Codex теперь сохраняет структурированные вызовы инструментов из файлов выполнения.'),
    @('Embeddings via the LiteLLM SDK can now optionally specify output dimensions.', 'При создании векторов через LiteLLM SDK можно задать размерность результата.'),
    @('API responses now include an X-Ignored-Params header to warn when unknown request parameters were ignored.', 'Ответы API теперь содержат заголовок X-Ignored-Params, если неизвестные параметры запроса были пропущены.'),
    @('OpenClaw CLI startup is faster by deferring heavy initialization until the service starts.', 'Командная строка OpenClaw запускается быстрее: тяжёлая инициализация отложена до запуска службы.'),
    @('Mental model triggers now support the full config schema, including tag matching and tag group filters.', 'Триггеры ментальной модели теперь поддерживают всю схему настроек, включая совпадение тегов и фильтры их групп.'),
    @('Cohere reranking via Azure endpoints now works reliably (avoids 404 errors).', 'Переранжирование Cohere через адреса Azure теперь работает без ошибок 404.'),
    @('Claude Code provider no longer defers to built-in tools, preventing MCP tool handling issues.', 'Поставщик Claude Code больше не передаёт работу встроенным инструментам, что устраняет ошибки обработки MCP.'),
    @('Recall endpoint now returns metadata correctly instead of dropping it from the response.', 'Конечная точка recall теперь возвращает метаданные, не пропуская их в ответе.'),
    @('Gemini 3.1+ tool calls now read thought signatures correctly.', 'Вызовы инструментов Gemini 3.1+ теперь верно читают подписи мыслей.'),
    @('First-person agent memories are now correctly classified as "experience" facts.', 'Записи памяти агента от первого лица теперь верно считаются фактами типа "experience".'),
    @('Codex upgrades now preserve and merge new settings instead of skipping them.', 'При обновлении Codex новые настройки теперь сохраняются и объединяются с прежними, а не пропускаются.'),
    @('LlamaIndex integration fixes improve document ID handling, memory API behavior, and ReAct tracing.', 'В интеграции LlamaIndex улучшена работа с ID документов, API памяти и трассировкой ReAct.'),
    @('Added audit logging for feature usage tracking, including request duration in audit entries.', 'Добавлен журнал аудита использования функций; записи содержат время запроса.'),
    @('Added Hindsight memory integration for the OpenAI Codex CLI.', 'Добавлена интеграция памяти Hindsight с OpenAI Codex CLI.'),
    @('Added an MCP hook to filter tool visibility per user.', 'Добавлен хук MCP для выбора видимых инструментов по пользователю.'),
    @('Added a per-bank limit setting to cap the number of observations stored per scope.', 'Для каждого банка можно ограничить число наблюдений в каждой области.'),
    @('Added native Windows support so Hindsight can run without Docker.', 'Добавлена встроенная поддержка Windows: Hindsight может работать без Docker.'),
    @("Added a 'none' LLM provider to support chunk-only storage without LLM calls.", 'Добавлен поставщик модели "none" для хранения лишь частей текста без вызовов модели.'),
    @('Added a setup command/skill to register hooks more reliably.', 'Добавлена команда и навык настройки для надёжной регистрации хуков.'),
    @('Hermes now supports file-based configuration.', 'Hermes теперь поддерживает настройку через файл.'),
    @('Added a LiteLLM-based provider to support Bedrock and many additional LLM providers.', 'Добавлен поставщик на базе LiteLLM с поддержкой Bedrock и многих других моделей.'),
    @('Added support for Strands Agents SDK integration with Hindsight memory tools.', 'Добавлена интеграция Strands Agents SDK с инструментами памяти Hindsight.'),
    @('Added LlamaIndex integration.', 'Добавлена интеграция LlamaIndex.'),
    @('Added AG2 framework integration.', 'Добавлена интеграция с фреймворком AG2.'),
    @('Added support for Ark and Volcano LLM providers.', 'Добавлена поддержка поставщиков языковых моделей Ark и Volcano.'),
    @('Retain now supports delta mode to skip LLM processing for unchanged chunks on upsert.', 'При обновлении документа режим delta пропускает вызовы модели для частей текста без изменений.'),
    @('Claude Code integration can now retain full sessions with document upsert and configurable tags, and records tool calls as structured JSON.', 'Интеграция Claude Code теперь сохраняет целые сеансы с обновлением документов и настраиваемыми тегами, а вызовы инструментов пишет как структурированный JSON.'),
    @('MCP retain tool now supports selecting a retain strategy via a parameter.', 'В инструменте MCP для сохранения памяти можно выбрать стратегию параметром.'),
    @('OpenClaw logging is now configurable and can emit structured output.', 'Журналы OpenClaw теперь настраиваются и могут иметь структурированный формат.'),
    @('Made inclusion of source facts in search observations configurable.', 'Включение исходных фактов в наблюдения поиска теперь настраивается.'),
    @('Integrations no longer use hardcoded default models, relying on configured defaults instead.', 'Интеграции больше не берут жёстко заданные модели по умолчанию, а используют заданные настройки.'),
    @('Improved MCP server compatibility by handling Claude Code GET probes and allowing stateless HTTP mode to be configured.', 'Сервер MCP теперь обрабатывает проверочные GET-запросы Claude Code и поддерживает настройку HTTP-режима без состояния.'),
    @('Per-bank vector index creation now respects the configured vector extension setting.', 'Создание векторного индекса для банка теперь учитывает выбранное векторное расширение.'),
    @('Verbose retain extraction now correctly includes the retain mission context.', 'Подробный вывод извлечения при сохранении теперь включает контекст задачи сохранения.'),
    @('Codex integration no longer crashes on startup when the API quota is exhausted (HTTP 429).', 'Интеграция Codex больше не срывает запуск при исчерпании квоты API (HTTP 429).'),
    @('OpenAI embeddings client now correctly parses query parameters included in base_url.', 'Клиент векторов OpenAI теперь верно разбирает параметры запроса в base_url.'),
    @('Fixed tool_choice handling for Codex/Claude Code when forcing specific tool calls.', 'Исправлена обработка tool_choice в Codex и Claude Code при принудительном вызове инструмента.'),
    @('OpenClaw auto-recall now supports a configurable timeout to prevent hangs.', 'Для автоизвлечения памяти OpenClaw теперь можно задать время ожидания, чтобы избежать зависаний.'),
    @('Fixed control plane UI issues affecting recall and data viewing.', 'Исправлены ошибки Control Plane при извлечении памяти и просмотре данных.'),
    @('Recall responses now include associated metadata.', 'Ответы recall теперь содержат связанные метаданные.'),
    @('Python client update_bank_config() now exposes all configurable fields.', 'Метод update_bank_config() клиента Python теперь даёт доступ ко всем настраиваемым полям.'),
    @('API OpenAPI schema now correctly includes Pydantic v2 ValidationError fields.', 'Схема OpenAPI теперь верно содержит поля ValidationError из Pydantic v2.'),
    @('JSON-string tags are now coerced to lists for MemoryItem and MCP tools to prevent tagging errors.', 'Теги в виде JSON-строки теперь превращаются в списки для MemoryItem и инструментов MCP, чтобы избежать ошибок.'),
    @('Add a one-command setup CLI package for the NemoClaw integration.', 'Добавлен пакет с одной командой настройки интеграции NemoClaw.'),
    @('Add a LangGraph integration for using Hindsight memory within LangGraph agents.', 'Добавлена интеграция LangGraph для работы агентов с памятью Hindsight.'),
    @('Add reflect filters to exclude specific fact types and mental model content during reflection.', 'В reflect добавлены фильтры для исключения отдельных типов фактов и текста ментальных моделей.'),
    @('Introduce independent versioning for integrations so they can be released separately from the core server.', 'Интеграции получили отдельные версии и могут выходить независимо от основного сервера.'),
    @('Add a Claude Code integration plugin.', 'Добавлен плагин интеграции Claude Code.'),
    @("Add a wall-clock timeout to reflect operations so they don’t run indefinitely.", 'Для reflect задан предел времени по часам, чтобы операции не шли бесконечно.'),
    @('Provide richer context when validating operations via the OperationValidator extension.', 'Расширение OperationValidator теперь получает больше контекста при проверке операций.'),
    @('Make the hindsight-api package runnable directly via uvx by adding script entry points.', 'Пакет hindsight-api теперь можно запускать прямо через uvx благодаря точкам входа скриптов.'),
    @('Support passing query parameters during OpenAI-compatible client initialization for broader provider compatibility.', 'При запуске клиента API в формате OpenAI теперь можно передавать параметры запроса для совместимости с большим числом поставщиков.'),
    @('Upgrade the default MiniMax model from M2.5 to M2.7.', 'Модель MiniMax по умолчанию обновлена с M2.5 до M2.7.'),
    @('Prevent context overflow during observation search by disabling source facts in results.', 'Во время поиска наблюдений исходные факты исключены из результатов, чтобы контекст не переполнялся.'),
    @('Fix Claude Code integration session startup by pre-starting the daemon in the background.', 'Для запуска сеанса Claude Code фоновая служба теперь запускается заранее.'),
    @('Fix Claude Code integration installation and configuration experience so setup is more reliable.', 'Улучшены установка и настройка интеграции Claude Code.'),
    @('Fix a memory leak in entity resolution that could grow over time under load.', 'Исправлена утечка памяти при поиске сущностей, которая росла со временем под нагрузкой.'),
    @('Avoid crashes and retain failures when the Postgres pg_trgm extension is unavailable by handling detection/fallback correctly.', 'Если расширение Postgres pg_trgm недоступно, система теперь верно обнаруживает это и выбирает запасной путь без сбоя сохранения.'),
    @('Strip Markdown code fences from model outputs across all LLM providers for more consistent parsing.', 'Из ответов всех поставщиков моделей удаляются блоки кода Markdown для более точного разбора.'),
    @('Return a clear 400 error for empty recall queries and fix a SQL parameterization issue.', 'Пустой запрос recall теперь получает ясную ошибку 400; исправлена передача параметров SQL.'),
    @('Ensure file retain requests include authentication headers so uploads work in authenticated deployments.', 'Запросы сохранения файлов теперь содержат заголовки авторизации, чтобы загрузка работала при включённом входе.'),
    @('Fix MCP tool calls when MCP_AUTH_TOKEN and TENANT_API_KEY differ.', 'Исправлены вызовы инструментов MCP, когда MCP_AUTH_TOKEN и TENANT_API_KEY различаются.'),
    @('Allow claude-agent-sdk to install correctly on Linux/Docker environments.', 'Пакет claude-agent-sdk теперь верно ставится в Linux и Docker.'),
    @('In LiteLLM mode, fall back to the last user message when no explicit hindsight query is provided.', 'В режиме LiteLLM при отсутствии явного запроса к Hindsight берётся последнее сообщение пользователя.'),
    @('Fix non-atomic async operation creation to prevent inconsistent operation records.', 'Создание асинхронной операции стало атомарным, чтобы записи не расходились.'),
    @('Prevent orphaned parent operations when a batch retain child fails unexpectedly.', 'При внезапном сбое дочерней задачи пакетного сохранения основная операция больше не остаётся без связанной задачи.'),
    @('Fix failures for non-ASCII entity names by ensuring entity IDs are set correctly.', 'ID сущностей с именами вне ASCII теперь задаются верно и не вызывают сбой.'),
    @('Correctly store LLM facts labeled as "assistant" as "experience" in the database.', 'Факты модели с меткой "assistant" теперь хранятся в базе как "experience".'),
    @('TypeScript client now works in Deno environments.', 'Клиент TypeScript теперь работает в среде Deno.'),
    @('Added Agno integration to use Hindsight as a memory toolkit.', 'Добавлена интеграция Agno, где Hindsight служит набором инструментов памяти.'),
    @('Added Hermes Agent integration (hindsight-hermes) for persistent memory.', 'Добавлена интеграция Hermes Agent (hindsight-hermes) с долговременной памятью.'),
    @('Expanded retain behavior with new `verbatim` and `chunks` extraction modes and named retain strategies.', 'В сохранение памяти добавлены режимы извлечения `verbatim` и `chunks` и именованные стратегии.'),
    @('Improved local reranker performance/efficiency with FP16 and bucketed batching, plus compatibility with Transformers 5.x.', 'Локальное переранжирование ускорено за счёт FP16 и партий по группам размеров; добавлена совместимость с Transformers 5.x.'),
    @('Prevented silent memory loss when consolidation fails (failed consolidations are tracked and can be recovered).', 'При сбое консолидации память больше не теряется незаметно: сбои учитываются, работу можно восстановить.'),
    @('Fixed Docker control-plane startup to respect the configured control-plane hostname.', 'Control Plane в Docker теперь учитывает заданное имя сервера при запуске.'),
    @('Database cleanup migration now removes orphaned observation memory units to avoid inconsistent memory state.', 'Миграция очистки базы теперь удаляет наблюдения без исходной памяти, чтобы не оставлять несогласованные записи.'),
    @('Deleting a document now also deletes linked memory units to prevent leftover/stale memory entries.', 'При удалении документа удаляются и связанные элементы памяти.'),
    @('Fixed MCP middleware to send an Accept header, preventing 406 response errors in some setups.', 'Промежуточный слой MCP теперь отправляет заголовок Accept, чтобы избежать ошибки 406.'),
    @('Improved compatibility with Gemini tool-calling by preserving thought signature metadata to avoid failures on gemini-3.1-flash-lite-preview.', 'При вызовах инструментов Gemini теперь сохраняется подпись мыслей, чтобы gemini-3.1-flash-lite-preview не сбоил.'),
    @('Add compound tag filtering using tag groups.', 'Добавлена составная фильтрация тегов через группы тегов.'),
    @('Publish new slim Python packages (hindsight-api-slim and hindsight-all-slim) for smaller installs.', 'Выпущены облегчённые пакеты Python hindsight-api-slim и hindsight-all-slim для меньшей установки.'),
    @('Add MiniMax as a supported LLM provider.', 'Добавлена поддержка MiniMax как поставщика языковых моделей.'),
    @('Add Jina MLX reranker provider optimized for Apple Silicon.', 'Добавлен поставщик переранжирования Jina MLX, настроенный для Apple Silicon.'),
    @('Allow configuring maximum recall query tokens via an environment variable.', 'Предел токенов запроса поиска памяти можно задать через переменную среды.'),
    @('Improve retrieval performance by switching to per-bank HNSW indexes.', 'Поиск ускорен за счёт отдельных индексов HNSW для каждого банка.'),
    @('Prevent reranking failures by truncating long documents that exceed LiteLLM reranker context limits.', 'Длинные документы теперь обрезаются до предела контекста переранжирования LiteLLM, чтобы избежать сбоев.'),
    @('Ensure recalled memories are injected as system context for OpenClaw.', 'Извлечённая память OpenClaw теперь вставляется как системный контекст.'),
    @('Ensure embedded profiles are registered in CLI metadata when the daemon starts.', 'При запуске фоновой службы встроенные профили регистрируются в метаданных командной строки.'),
    @('Cancel in-flight async operations when a bank is deleted to avoid dangling work.', 'При удалении банка незавершённые асинхронные операции отменяются.'),
    @('Added a manual retry option for failed asynchronous operations.', 'Для сбойных асинхронных операций добавлен ручной повтор.'),
    @('You can now change/update tags on an existing document.', 'Теги существующего документа теперь можно менять.'),
    @('Added history tracking and a diff view for mental model changes.', 'Для ментальных моделей добавлены история изменений и просмотр различий.'),
    @('Added observation history tracking with a UI diff view to review changes over time.', 'Для наблюдений добавлены история и просмотр различий в интерфейсе.'),
    @('File uploads can now choose a parser per request, with configurable fallback chains.', 'При загрузке файла можно выбрать способ разбора для каждого запроса и настроить цепочку запасных вариантов.'),
    @('Added an extension hook that runs after file-to-Markdown conversion completes.', 'Добавлен хук расширения, который срабатывает после перевода файла в Markdown.'),
    @('Operations view now supports filtering by operation type and has more reliable auto-refresh behavior.', 'Список операций теперь фильтруется по типу и надёжнее обновляется сам.'),
    @('Added token limits for “source facts” used during consolidation and recall to better control context usage.', 'Для исходных фактов при консолидации и поиске памяти добавлены лимиты токенов.'),
    @('Improved bank selector usability by truncating very long bank names in the dropdown.', 'В списке банков очень длинные имена теперь обрезаются.'),
    @('Fixed webhook schema issues affecting multi-tenant retain webhooks.', 'Исправлена схема вебхуков сохранения памяти для нескольких арендаторов.'),
    @('Fixed file ingestion failures by stripping null bytes from parsed file content before retaining.', 'Перед сохранением из текста файлов удаляются нулевые байты, которые вызывали сбой загрузки.'),
    @('Fixed tool selection handling for OpenAI-compatible providers when using named tool_choice.', 'Исправлен выбор инструментов у поставщиков API в формате OpenAI при именованном tool_choice.'),
    @("Improved consolidation behavior to prioritize a bank’s mission over an ephemeral-state heuristic.", 'При консолидации задача банка теперь важнее эвристики временного состояния.'),
    @('Fixed database migrations to correctly handle mental model embedding dimension changes.', 'Миграции базы теперь верно обрабатывают смену размерности векторов ментальной модели.'),
    @('Fixed file upload failures caused by an Iris parser httpx read timeout.', 'Исправлены сбои загрузки файлов из-за времени ожидания httpx в разборщике Iris.'),
    @('Improved reliability of running migrations by serializing Alembic upgrades within the process.', 'Обновления Alembic внутри процесса теперь идут по очереди для надёжной миграции.'),
    @('Fixed Google Cloud Storage authentication when using Workload Identity Federation credentials.', 'Исправлен вход в Google Cloud Storage с учётными данными Workload Identity Federation.'),
    @('Fixed the bank selector to refresh the bank list when the dropdown is opened.', 'Список банков теперь обновляется при открытии меню.'),
    @('Added Webhooks with `consolidation.completed` and `retain.completed` events.', 'Добавлены вебхуки с событиями `consolidation.completed` и `retain.completed`.'),
    @('Improved OpenClaw recall/retention controls.', 'Улучшены настройки извлечения и сохранения памяти в OpenClaw.'),
    @('Improved search/reranking quality by switching combined scoring to multiplicative boosts.', 'Качество поиска и переранжирования улучшено за счёт умножения весов в общей оценке.'),
    @('Improved performance of observation recall by 40x on large banks.', 'Поиск наблюдений в больших банках ускорен в 40 раз.'),
    @('Improved server shutdown behavior by capping graceful shutdown time and allowing a forced kill on a second Ctrl+C.', 'Для штатной остановки сервера задан предел времени; второе Ctrl+C завершает его принудительно.'),
    @('Fixed an async deadlock risk by running database schema migrations in a background thread during startup.', 'Миграции схемы базы при запуске теперь идут в фоновом потоке, чтобы избежать взаимной блокировки.'),
    @("Fixed webhook delivery/outbox processing so transactions don’t silently roll back due to using the wrong database schema name.", 'При доставке вебхуков и обработке исходящей очереди теперь берётся верное имя схемы базы, чтобы транзакции не откатывались без сообщения.'),
    @('Fixed observation results to correctly resolve and return related chunks using source_memory_ids.', 'Результаты наблюдений теперь верно находят и возвращают связанные части через source_memory_ids.'),
    @('Fixed MCP bank-level tool filtering compatibility with FastMCP 3.x.', 'Исправлена совместимость фильтрации инструментов MCP по банкам с FastMCP 3.x.'),
    @('Fixed crashes when an LLM returns invalid JSON across all retries (now handled cleanly instead of raising a TypeError).', 'Если модель возвращает неверный JSON во всех попытках, ошибка теперь обрабатывается без сбоя TypeError.'),
    @('Fixed observations without source dates to preserve missing (None) temporal fields instead of incorrectly populating them.', 'У наблюдений без даты источника временные поля теперь остаются None, а не заполняются неверно.'),
    @('Added observation_scopes to control the granularity/visibility of observations.', 'Добавлены observation_scopes для выбора уровня детализации и видимости наблюдений.'),
    @('List documents API now supports filtering by tags (and fixes the q parameter description).', 'API списка документов теперь поддерживает фильтр по тегам; описание параметра q исправлено.'),
    @('Added PydanticAI integration for persistent agent memory.', 'Добавлена интеграция PydanticAI с долговременной памятью агентов.'),
    @('Added richer entity label support (optional labels, free-form values, multi-value fields, and UI polish).', 'Расширены метки сущностей: необязательные метки, свободные значения, поля с несколькими значениями и улучшенный интерфейс.'),
    @('Added support for timestamp="unset" so content can be retained without a date.', 'Добавлено значение timestamp="unset" для сохранения текста без даты.'),
    @('OpenClaw can now automatically retain the last n+2 turns every n turns (default n=10).', 'OpenClaw может автоматически сохранять последние n+2 реплики каждые n ходов (по умолчанию n=10).'),
    @('Added configurable Gemini/Vertex AI safety settings for LLM calls.', 'Добавлены настройки безопасности Gemini и Vertex AI для вызовов языковой модели.'),
    @('Added extension hooks to customize root routing and error headers.', 'Добавлены хуки расширений для настройки основного маршрута и заголовков ошибок.'),
    @('Improved recall performance by fetching all recall chunks in a single query.', 'Поиск памяти ускорен: все части извлекаются одним запросом.'),
    @('Improved recall/retain performance and scalability for large memory banks.', 'Ускорены поиск и сохранение памяти в больших банках.'),
    @('Fixed the TypeScript SDK to send null (not undefined) when includeEntities is false.', 'SDK TypeScript теперь передаёт null, а не undefined, когда includeEntities равно false.'),
    @('Prevented reflect from failing with context_length_exceeded on large memory banks.', 'Reflect больше не срывается с context_length_exceeded на больших банках памяти.'),
    @('Fixed a consolidation deadlock caused by retrying after zombie processing tasks.', 'Исправлена взаимная блокировка консолидации при повторах после зависших задач.'),
    @('Fixed observations count in the control plane that always showed 0.', 'Счётчик наблюдений в Control Plane больше не показывает всегда 0.'),
    @('Fixed ZeroEntropy rerank endpoint URL and ensured the MCP retain async_processing parameter is handled correctly.', 'Исправлен URL переранжирования ZeroEntropy и обработка параметра async_processing в сохранении через MCP.'),
    @('Fixed JSON serialization issues and logging-related exception propagation when using the claude_code LLM provider.', 'Исправлены запись JSON и передача ошибок журналов при работе с поставщиком модели claude_code.'),
    @('Added bank-scoped request validation to prevent cross-bank/invalid bank operations.', 'Добавлена проверка запросов в пределах банка, чтобы исключить ошибки банка и операции между банками.')
)
$content = [IO.File]::ReadAllText($path, [Text.Encoding]::UTF8)
foreach ($pair in $pairs) { $content = $content.Replace($pair[0], $pair[1]) }
[IO.File]::WriteAllText($path, $content, [Text.UTF8Encoding]::new($false))
